
// PHASE 1: THE DATA ONTOLOGY

export enum TagType {
    CATEGORICAL = 'CATEGORICAL', // Subject, Location
    QUALITATIVE = 'QUALITATIVE', // Mood, Texture, Abstract
    TECHNICAL = 'TECHNICAL',     // Camera, Lens (Auto-generated)
    SEASONAL = 'SEASONAL',        // Auto-generated
    AI_GENERATED = 'AI_GENERATED' // Generated by CLIP Smart Search
}

export interface Tag {
    id: string;
    label: string;
    type: TagType;
}

// Define SimulationNodeDatum manually to avoid d3 module resolution issues
export interface SimulationNodeDatum {
    index?: number;
    x?: number;
    y?: number;
    vx?: number;
    vy?: number;
    fx?: number | null;
    fy?: number | null;
}

// D3 SimulationNodeDatum extension for physics
export interface SimulationNode extends SimulationNodeDatum {
    id: string; // Required by D3
    r?: number; // Radius
}

export interface ImageNode extends SimulationNode {
    id: string; // UUID
    fileUrl: string; // Placeholder URL
    fileName: string; // Original filename for persistence logic
    
    // Temporal Data
    captureTimestamp: number; // Unix timestamp
    inferredSeason: string;
    shootDayClusterId: string; // YYYY-MM-DD

    // Technical Data
    cameraModel: string;
    lensModel: string;
    aperture: string;
    shutterSpeed: string;
    iso: number;

    // Relational
    tagIds: string[];
    aiTagIds: string[]; // Tags generated by CLIP Smart Search

    // Visual Data
    palette: string[]; // 5-color Hex Palette

    // URLs
    originalUrl?: string; // Full-res original from Immich
    
    // UI State
    selected?: boolean;
}

// Extended Node for Experience/Simulation View
export interface ExperienceNode extends SimulationNodeDatum {
    id: string;
    original: ImageNode;
    // D3 coordinates (made explicit)
    x: number; 
    y: number;
    vx?: number;
    vy?: number;
    
    // Visual State
    currentScale: number;
    targetScale: number;
    currentOpacity: number;
    targetOpacity: number;
    relevanceScore: number;
    scoreBreakdown?: ScoreBreakdown;
    isVisible: boolean;
    
    // Orbit/Grid Props (Procedural Layouts)
    orbitSpeed?: number;
    orbitOffset?: number;
    orbitRadiusBase?: number;
    gridSortIndex?: number;

    // Orbital Ring Props (2.5D Navigation)
    ringProfile?: RingProfile;
    glyphContext?: GlyphContext;
    depthLayer?: DepthLayer;
}

export interface InsightSnapshot {
    id: string;
    timestamp: number;
    description: string;
    activeFilterTags: string[];
    zoomLevel: number;
    centerPoint: { x: number, y: number };
}

export type ViewMode = 'WORKBENCH' | 'EXPERIENCE';
export type ExperienceMode = 'EXPLORE' | 'HISTORY';

export type AnchorMode = 'NONE' | 'IMAGE' | 'TAG' | 'COLOR' | 'DATE' | 'CAMERA' | 'LENS' | 'SEASON';

export interface AnchorState {
    mode: AnchorMode;
    id: string; // UUID, TagID, Hex Color, Timestamp (string), or Model Name
    meta?: any; // Tag object, Color string, etc.
}

export interface ScoreBreakdown {
    total: number;
    temporal: number;
    thematic: number;
    visual: number;
    technical: number;
}

export interface PhysicsConfig {
    velocityDecay: number;
    velocityDecayIdle: number;
    swirlSpeed: number;
    floatPerturbation: number;
    floatSpeed: number;
    heroGravity: number;
    neighborGravity: number;
    zoneGravity: number;
    localSwirlSpeed: number;
    gridPull: number;
    filterGridPull: number;
    damping: number;
    lerpVisible: number;
    lerpHidden: number;
    boundaryScale: number;
    heroEquilibriumGravity: number;
    heroVelocityDamping: number;
    cameraPanSpeed: number;
    comfortZoneRatio: number;
    ringRadii: Record<RingLevel, number>;
    ringRadiiMobile: Record<RingLevel, number>;
    ringGravity: number;
}

export type ZoneName = 'temporal' | 'thematic' | 'visual' | 'technical';

// --- ORBITAL RINGS (2.5D Navigation) ---

export type RingLevel = 'session' | 'thematic' | 'visual' | 'technical' | 'gateway';

export interface RingProfile {
    ring: RingLevel;
    dominantDimension: ZoneName | null;
    normalizedScores: Record<ZoneName, number>;
    isSameDay: boolean;
}

export interface GlyphContext {
    affinityColor: string;
    haloColor: string;
    haloIntensity: number;
    relevanceScale: number;
    shapeKey: RingLevel;
    ringProfile: RingProfile;
}

export interface DepthLayer {
    z: number;
    blur: number;
    opacity: number;
    parallaxFactor: number;
}

export interface ZoneSummary {
    zone: ZoneName;
    count: number;
    label: string;      // "Same Session", "Portrait, Studio", "Warm Tones", "X-T4"
    sublabel: string;   // "5 from Mar 2", "6 shared concepts", "4 palette matches"
}

export interface NeighborhoodSummary {
    zones: ZoneSummary[];
    totalNeighbors: number;
    narrative: string;   // Natural language paragraph
}

export interface ExperienceContext {
    commonTags: Tag[];
    activePalette: string[];
}
