
// PHASE 1: THE DATA ONTOLOGY

export enum TagType {
    CATEGORICAL = 'CATEGORICAL', // Subject, Location
    QUALITATIVE = 'QUALITATIVE', // Mood, Texture, Abstract
    TECHNICAL = 'TECHNICAL',     // Camera, Lens (Auto-generated)
    SEASONAL = 'SEASONAL',        // Auto-generated
    AI_GENERATED = 'AI_GENERATED' // Generated by Gemini
}

export interface Tag {
    id: string;
    label: string;
    type: TagType;
}

// Define SimulationNodeDatum manually to avoid d3 module resolution issues
export interface SimulationNodeDatum {
    index?: number;
    x?: number;
    y?: number;
    vx?: number;
    vy?: number;
    fx?: number | null;
    fy?: number | null;
}

// D3 SimulationNodeDatum extension for physics
export interface SimulationNode extends SimulationNodeDatum {
    id: string; // Required by D3
    r?: number; // Radius
}

export interface ImageNode extends SimulationNode {
    id: string; // UUID
    fileUrl: string; // Placeholder URL
    fileName: string; // Original filename for persistence logic
    
    // Temporal Data
    captureTimestamp: number; // Unix timestamp
    inferredSeason: string;
    shootDayClusterId: string; // YYYY-MM-DD

    // Technical Data
    cameraModel: string;
    lensModel: string;
    aperture: string;
    shutterSpeed: string;
    iso: number;

    // Relational
    tagIds: string[];
    aiTagIds: string[]; // Tags generated by AI
    tagVersion?: number; // 0 or undefined = Initial, 1 = Harmonized (v1.0)
    
    // Visual Data
    palette: string[]; // 5-color Hex Palette
    
    // UI State
    selected?: boolean;
}

// Extended Node for Experience/Simulation View
export interface ExperienceNode extends SimulationNodeDatum {
    id: string;
    original: ImageNode;
    // D3 coordinates (made explicit)
    x: number; 
    y: number;
    vx?: number;
    vy?: number;
    
    // Visual State
    currentScale: number;
    targetScale: number;
    currentOpacity: number;
    targetOpacity: number;
    relevanceScore: number;
    isVisible: boolean;
    
    // Orbit/Grid Props (Procedural Layouts)
    orbitSpeed?: number;
    orbitOffset?: number;
    orbitRadiusBase?: number;
    gridSortIndex?: number;
}

export interface InsightSnapshot {
    id: string;
    timestamp: number;
    description: string;
    activeFilterTags: string[];
    zoomLevel: number;
    centerPoint: { x: number, y: number };
}

export type ViewMode = 'WORKBENCH' | 'EXPERIENCE';
export type ExperienceMode = 'EXPLORE' | 'HISTORY';

export type AnchorMode = 'NONE' | 'IMAGE' | 'TAG' | 'COLOR' | 'DATE' | 'CAMERA' | 'LENS' | 'SEASON';

export interface AnchorState {
    mode: AnchorMode;
    id: string; // UUID, TagID, Hex Color, Timestamp (string), or Model Name
    meta?: any; // Tag object, Color string, etc.
}

export interface ExperienceContext {
    commonTags: Tag[];
    activePalette: string[];
}
