
// PHASE 1: THE DATA ONTOLOGY

export enum TagType {
    CATEGORICAL = 'CATEGORICAL', // Subject, Setting
    QUALITATIVE = 'QUALITATIVE', // Mood, Style
    TECHNICAL = 'TECHNICAL',     // Camera, Lens, Lighting (Auto-generated)
    SEASONAL = 'SEASONAL',        // Auto-generated
    AI_GENERATED = 'AI_GENERATED' // Generated by AI tagging pipeline
}

// Tag categories from the Ollama tagging pipeline
export type TagCategory = 'mood' | 'lighting' | 'subject' | 'setting' | 'style';

export const TAG_CATEGORIES: TagCategory[] = ['mood', 'lighting', 'subject', 'setting', 'style'];

export const TAG_CATEGORY_LABELS: Record<TagCategory, string> = {
    mood: 'Mood',
    lighting: 'Lighting',
    subject: 'Subject',
    setting: 'Setting',
    style: 'Style',
};

// Map tag categories to TagType for scoring weights
export const TAG_CATEGORY_TYPE: Record<TagCategory, TagType> = {
    mood: TagType.QUALITATIVE,
    lighting: TagType.TECHNICAL,
    subject: TagType.CATEGORICAL,
    setting: TagType.CATEGORICAL,
    style: TagType.QUALITATIVE,
};

export interface Tag {
    id: string;
    label: string;
    type: TagType;
    category?: TagCategory; // Set for Ollama-generated tags (mood, lighting, subject, setting, style)
}

export interface ImageNode {
    id: string; // UUID
    fileUrl: string; // Placeholder URL
    fileName: string; // Original filename for persistence logic

    // Temporal Data
    captureTimestamp: number; // Unix timestamp
    inferredSeason: string;
    shootDayClusterId: string; // YYYY-MM-DD

    // Technical Data
    cameraModel: string;
    lensModel: string;
    aperture: string;
    shutterSpeed: string;
    iso: number;
    focalLength: number | null; // mm (from EXIF)

    // Relational
    tagIds: string[];
    aiTagIds: string[]; // Tags generated by AI tagging pipeline

    // Visual Data
    palette: string[]; // 5-color Hex Palette

    // URLs
    originalUrl?: string; // Full-res original from Immich

    // UI State
    selected?: boolean;
}
